inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
  family: gpt2
  n_dims: 20
  n_embd: 128
  n_head: 8
  n_layer: 4
  n_positions: 101

training:
  batch_size: 32
  curriculum:
    dims:
      start: 5
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 6
      end: 30
      inc: 2
      interval: 2000
  data: gaussian
  data_kwargs: {}
  keep_every_steps: 100000
  learning_rate: 0.0003
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 100
  task: noisy_linear_regression
  task_kwargs: {
    # "compute_gradient": True
    # "sparsity": 5
  } 
  train_steps: 50001

out_dir: /content/models/sparse_linear_regression

wandb:
    name: "sparse_linear_regression_standard"
